apiVersion: mutations.gatekeeper.sh/v1beta1
kind: Assign
metadata:
  name: node-csr-clusterissuer-mutation
spec:
  applyTo:
  - groups: ["certificates.k8s.io"]
    kinds: ["CertificateSigningRequest"]
    versions: ["v1"]
  match:
    scope: Cluster
    kinds:
    - apiGroups: ["*"]
      kinds: ["CertificateSigningRequest"]

  location: "spec.signerName"
  parameters:
    assign:
      value: "clusterissuers.cert-manager.io/vault-issuer"