# NOTE: this manifest is only compatible with Kubernetes versions >=v1.21

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-controller-manager
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: yandex-cloud-controller-manager
  labels:
    k8s-app: yandex-cloud-controller-manager
spec:
  selector:
    matchLabels:
      k8s-app: yandex-cloud-controller-manager
  template:
    metadata:
      labels:
        k8s-app: yandex-cloud-controller-manager
    spec:
      hostNetwork: true
      dnsPolicy: Default
      serviceAccountName: cloud-controller-manager
      nodeSelector:
        # The CCM will only run on masters
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: node-role.kubernetes.io/master
        - key: node-role.kubernetes.io/control-plane
        - key: node.kubernetes.io/not-ready
        - key: node.kubernetes.io/out-of-disk
        - key: node.kubernetes.io/memory-pressure
        - key: node.kubernetes.io/disk-pressure
        - key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
          effect: NoSchedule
      containers:
        - image: registry.deckhouse.io/yandex-cloud-controller-manager/yandex-cloud-controller-manager:v0.21.3
          name: yandex-cloud-controller-manager
          command:
            - /bin/yandex-cloud-controller-manager
            - --cloud-provider=yandex
            - --v=3
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
          env:
            - name: YANDEX_CLOUD_SERVICE_ACCOUNT_JSON
              valueFrom:
                secretKeyRef:
                  name: yandex-cloud
                  key: service-account-json
            - name: YANDEX_CLOUD_FOLDER_ID
              valueFrom:
                secretKeyRef:
                  name: yandex-cloud
                  key: folder-id
            - name: YANDEX_CLOUD_DEFAULT_LB_TARGET_GROUP_NETWORK_ID
              valueFrom:
                secretKeyRef:
                  name: yandex-cloud
                  key: vpc-id    
            - name: YANDEX_CLOUD_INTERNAL_NETWORK_IDS
              valueFrom:
                secretKeyRef:
                  name: yandex-cloud
                  key: vpc-id
            - name: YANDEX_CLUSTER_NAME
              value: {{ .Values.cluster_name }}
