
machineContoller:
  namespace: kube-fraima-ccm

clusterUrl: ${k8s_api_server_fqdn}
clusterPort: ${k8s_api_server_port}

replicas: ${replicas}
minReadySeconds: 300

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  type: RollingUpdate

selector:
  matchLabels:
    instance-group: monitoring

template:
  metadata:
    labels:
      instance-group: monitoring
    nodeLabels:
      node-role.kubernetes.io/monitoring: ""
      provider: yandex
    cloudLabels:
      treska: critical
      
  spec:
    bootDisk:
      imageID: ${image_id}
      typeID: network-hdd
      autoDelete: true
      size: 20

    resources:
      cpu: 8
      coreFraction: 20
      memory: 8

    networkInterfaces:
      nat: true
      regionID: ru-central1
      subnetID: "${subnet_id}"
      zoneID: "${zone}"
      networkType: STANDARD

    provider:
      type: YandexCloud
      name: yandex-cloud-controller
