---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cert-manager-vault-approle
  namespace: fraima-certmanager
data:
  secretId: {{ .Values.vault.approle.secretId }}

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    path: {{ .Values.vault.sign.path }}
    server: {{ .Values.vault.server }}
    caBundle: 
    auth:
      appRole:
        path: {{ .Values.vault.approle.path }}
        roleId: {{ .Values.vault.approle.roleId }}
        secretRef:
          name: cert-manager-vault-approle
          key: secretId