tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  - key: "CriticalAddonsOnly"
    operator: "Exists"
  - key: node.cloudprovider.kubernetes.io/uninitialized
    value: "true"
    effect: NoSchedule
resources:
  limits:
    cpu: 200m
    memory: 100Mi          
  requests:
    cpu: 100m
    memory: 50Mi

webhook:
  tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  - key: "CriticalAddonsOnly"
    operator: "Exists"
  - key: node.cloudprovider.kubernetes.io/uninitialized
    value: "true"
    effect: NoSchedule
  resources:
    limits:
      cpu: 200m
      memory: 100Mi          
    requests:
      cpu: 100m
      memory: 50Mi

cainjector:
  tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  - key: "CriticalAddonsOnly"
    operator: "Exists"
  - key: node.cloudprovider.kubernetes.io/uninitialized
    value: "true"
    effect: NoSchedule
  resources:
    limits:
      cpu: 200m
      memory: 100Mi          
    requests:
      cpu: 100m
      memory: 50Mi


startupapicheck:
  tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  - key: "CriticalAddonsOnly"
    operator: "Exists"
  - key: node.cloudprovider.kubernetes.io/uninitialized
    value: "true"
    effect: NoSchedule

featureGates: "ExperimentalCertificateSigningRequestControllers=true"
installCRDs: true
