helm repo add cilium https://helm.cilium.io/
helm install cilium cilium/cilium --version 1.12.0 \
    --namespace fraima-cni \
    --create-namespace \
    --set kubeProxyReplacement=strict \
    --set k8sServiceHost=api.cluster-1.dobry-kot.ru \
    --set k8sServicePort=6443

helm repo add jetstack https://charts.jetstack.io
helm upgrade \
  cert-manager jetstack/cert-manager \
  --install \
  --namespace fraima-certmanager \
  --create-namespace \
  --version v1.9.1 \
  --set installCRDs=true \
  --set featureGates="ExperimentalCertificateSigningRequestControllers=true"


---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    path: pki_int/sign/istio
    server: http://51.250.67.8:9200
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVZakNDQWtxZ0F3SUJBZ0lVQkM3YWVMRWZMMVlUMzMrOFlXM2FvMkVSTlJZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tqRUxNQWtHQTFVRUNCTUNRMEV4R3pBWkJnTlZCQU1URWt0MVltVnlibVYwWlhNZ1VtOXZkQ0JEUVRBZQpGdzB5TWpBNU1qTXhPRFUwTWpkYUZ3MHpNakV4TWpreE9EVTBOVGRhTUVjeEN6QUpCZ05WQkFnVEFrTkJNUk13CkVRWURWUVFLRXdwTGRXSmxjbTVsZEdWek1TTXdJUVlEVlFRREV4cExkV0psY201bGRHVnpJRWx1ZEdWeWJXVmsKYVdGMFpTQkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLbjJ2d1hlZVhuUgpodlFONkR1YTJ3ZFNsM0FvUVRTbUVMa25PVFFDenZIRVA4RDN4SVNSZzFxZ1RPSWdQb09BdkZINzhZVGtGWUFtCkdaZlZZRVlHSjdYSlZNK1ZoNUI0OE1UWmFVclhuTEFjQWhjOFhyQk1PSC9reUROWHVxMHM2dlNLZlk1SkVOejUKMXlCVTNGNUVFcVRCb1UvNlI2R1h4LzIrRHJzdktVeGtWbkFjb0tnK2VWM095eFc0ZHlud05QUURMWWEzZmUwdgpBUzg3Z0JiMTBxUmYrbjd4WFRFdTJ1aHNzQXhZYXJ5RkhlQjJaMzQ5WDdDMFk5cHk3dEVnRnVYMjBGQ2svME5ECmZPeUZqd2NVcFI4dWlSK296bisvdyt2ZnJ2OVllVVQvUDY3RlpuZ3FZTThqL1lNUDFQVGYyMWJ2MlU4SVM2UDIKNTloVThvbE1SSlVDQXdFQUFhTmpNR0V3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGTUFNQgpBZjh3SFFZRFZSME9CQllFRkJ2bzFyakg0anhsQmhRbEJXQzdkd2dPVXptbE1COEdBMVVkSXdRWU1CYUFGSW9QCm8yV3hGTlFkandwVXVidFhwZGlRM09WdE1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQ2RFbEVhcDg3djhxelkKVmsrY0d3allqTGN6RUpLay8vT09aeTFncytjV1MxS0prUlhod29DbkFtV2NmY2JITGZHcmdPYXRnSy9BeGVBaQo0ZzBNeVRIdHEvMmpRcW9BWFlLRzRwUFAzZGF0bDhOVmlGUm5waHpaTjBIRDB3cEs5Z1p4QWlrakozWnlwcTR5CnNaMTFrQkRCMVM2YytRU0J4cHRUbkhMcm1aaW5aYVBSNHllam9BK3BLSUtTMzJNRzA0OUUzeDdJL29JbWdxUVUKMTUrZFhnVjB1eEhWSlQxcEszdi9NL1dFRG9OUS9POU9pMFpVZ05mbGJoSVE1TlBlMDZzU0QxN01VUkFabHlrUApmQWMwYlIrV3hUTkNSSlNZSmpsTXErVTV1YWpKN3JMNGJRVFlrRXZaazZtTTNiakY3MWUySE5MQTlnWGRrOWxwCjkrWjBvU1laaHg4U1BJT0x0enhqTFNHUkEwRkcyaGJxQlJBbkM3SEpMVmxjRVhuVk5UVytZSFZENGI1dXZNTVAKekRYNStDKzdnNzlNb3NJZmN1cUlzdEZmRndtWmNxb2J4a1U5WkEvV1R1SDJxMXo1NmhualBBejFMdU04aUZRQwpiaWVwR0xiRE0rZmxnamorSndLUGFEVjc1WmVJLzhtSlQ3ZGpieXcxRndBcC9OTDFVTW1odHpGaitBTXVLck1SCmw0b0JJSFRkQVloR2hRVTZ5Qnk4dTA1aDFEYjVTazAxSEplL1BRUWhYZy9QbXJPTSs4bXF4R0JOcmJIUGVJM0kKazd2SEo1Njl1WnJ6NzZrby9WbldmZVlHWmp2Yk5FOVJncGJPWVMyaklFRTNTZWdXN1lWZzJSbUs1d0lFckE0LwpWRmlqUkpKS2Y4aktubU90MkdNempXOHlvR3ozTUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
    auth:
      appRole:
        path: clusters/cluster-1/approle
        roleId: ad742abe-628d-435e-e680-d2a3b0475fa2
        secretRef:
          name: cert-manager-vault-approle
          key: secretId
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cert-manager-vault-approle
  namespace: fraima-certmanager
data:
  secretId: OGNjM2U3ZWYtMGZiNi1jYTU2LTg2NjctMGUxZDdhNmIyNGQ3

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-referencer:my-issuer
  namespace: sandbox
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["signers"]
  verbs:     ["reference"]
  resourceNames:
  - "*" 

---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: myuser
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJRWh6Q0NBbThDQVFBd1FqRUxNQWtHQTFVRUJoTUNXRmd4RlRBVEJnTlZCQWNNREVSbFptRjFiSFFnUTJsMAplVEVjTUJvR0ExVUVDZ3dUUkdWbVlYVnNkQ0JEYjIxd1lXNTVJRXgwWkRDQ0FpSXdEUVlKS29aSWh2Y05BUUVCCkJRQURnZ0lQQURDQ0Fnb0NnZ0lCQU1WYWVQeVltbEpzUnlNQkpweXRydUUxbkVVSE0vUkc1WnF3c24yUzd5dFcKTE9RMk10SUJUdndZQ0dZelV1TElZczVqOWxyM0QxUGdNTWN5RzlmMkNCK3UyczBoWWM2aFVqbFBoQTFlS21ISAp6MUREZW5PZ3BVR1hiL1RHam92anRUZEk4TlZsZkVqVjhxaVdueEh0eHd5TEl0a3JZV3QzR3FZc0JBVEpqSGh4CmoxYVFMdjdlSjIya0I1a3JDRWF4VlEwTU9OMzZrandBczJDT0gzQUVReDFKSXhsd0lITDdHMUxJbmZMVUl0S00KeXdlYTJQNlFsODNzQUx1WmRaR2JlT0UydGNXZCtTc3NQOG9KL0o4ZWRBZGUrVUZvVTRuY0E2bkFvT25VenpsRAptUG5TaUFycWZkbmdpN1pNazRMbDhIZmpDbVY3SzQzK1RpSzBYd08raHFucFFhd2tlMk16YXJkSVU3QVh2Z0FNCjBld1JpQWpyUERSc015Q3JaVWhDSHNJYUh6VU5KTlM1ZDh1U0c0cy91MUN6amRWSHdmYlMzSWx6eExQbWNGcFAKeFdZWm8rem1zcXdIU0d0UFhnVWpUN3dJUS82VElIMlk0K21iN1o2YmMrSnJnK05Vazg4N0MwVnAyKzhaaHN4Qwp0NElLdERqbTJIUWpOYVNvT0xUaDJ2dVFpYVFZNHhsK2Q3WTQvZldiSVlIYjBOMmc0cEFOZGpWQ0hQVVdnbng1CmZVOVY4d1ZvOFZrRWNLNnc0bDhiUDRIbG5ZTTE2Yml0OWE5T0NZTkg5Y09GSkdoMFltNU5EN2NoZnB0YUxEdk8KTTdUVFZHbkZ6NW5OL0I2WHlpMmZOVXRwZVJLMTlVTUd2Z1ppZEIyTGJjMGNHL0RpSm9PMjNRb2tQcDk1UWpvOQpBZ01CQUFHZ0FEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FnRUFvNXBOSFJqcVlIWEUzV2RodWZFQWNUV1FBM2g2CnBOeGVRY09la3hmNDdjSHovZnltZGo1Uk4zaS9ocHhEL3AzNE9tWUxFL0dRbUdSN0N0aVN4S1ljZ3VabEk1V3EKckYxdjR2L0hqRHZMdC9mSDRsMHR0MytIVFBweEdUQXpzWGJwekM5RHd1YWdSUVhNempOZmdyZnByQWZ3b2syNQpXWFhOcTM2YkZKY0FVUjJsRmM5blhHOFE4TkxvR3Z2TW9jd2tSL0hNZVF4R1g4YzNCaXp2WG5idFRxY2U2RkNnCkhwaWwvbERIdUtjSzdqZy9oZmpuRVh4L0xCalNHNEZaUUF6cUpscHUxWXpPR0oxRmFGQWdvT2k1S0tkQlpkREQKSjBIZjlCQkxrQkk5ZUJwbTJWczk2eTU0S0crYTZERi9qVis3WjAvU0JZc1lNenFVS0p3cWRoRmg5djl1cU1yKwpPLzFHRnV5MTBZM00vNTFPeVk4RnNPaGcvZUFUL3lGaE9UVEFaYUlVN0lZdU5VZ1V5VVo4VkFDYW5jVzhabHN3Cm5jUHh1RUp6alJacWNMdU5ZMkNBVThISG5wOVltdXRhREpkS0R1aVFnNldHbnFXTmJOWmhKSkI0UzFlbWlraS8KeTFVYStidDRFOE9FaG9VTjBQK0FrUW1OMWFLL2NIKzFHZmhtaHRXbEdPcVBUakg2b1Ixb3kraitDNmpWS1pkRQpNSkNySElSTWg3ZlI4MG1teGxRVElFdFFpLy9uSmpLamdqdit6QlNVYkN5eWJHa05JYzcxMnBxUUo5YmJibVdPCldROFlzNldRcXZhTTR0QXJ5UUxEYkVsSE0zM1Bvd2xyd1ZRblhKVlk1ZnJLOHBFcHBtNVB1SFExdFJFK1NwSzgKa3FOZWNFaGV3cXhMMk5rPQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  signerName: clusterissuers.cert-manager.io/vault-issuer
  expirationSeconds: 86400  # one day
  usages:
  - server auth


apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  creationTimestamp: "2022-09-23T23:46:14Z"
  generateName: csr-
  name: csr-spftp
  resourceVersion: "5874"
  uid: 63a7c507-bbc8-4fe6-8075-b3eb45712cfd
spec:
  groups:
  - system:nodes
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQlNqQ0I4Z0lCQURCTk1SVXdFd1lEVlFRS0V3eHplWE4wWlcwNmJtOWtaWE14TkRBeUJnTlZCQU1USzNONQpjM1JsYlRwdWIyUmxPbTFoYzNSbGNpMHhMbU5zZFhOMFpYSXRNUzVrYjJKeWVTMXJiM1F1Y25Vd1dUQVRCZ2NxCmhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUkVNRHhTTzNvK3R0TGFlUXVQM0c3anhSMmtFSXhDMjhoODFWMmEKMXhueUZybnByZys2V01FWkhFRHNkQ3NOS2ZpL24zU2N0eWQzVVVkMDVVVzlURm44b0VNd1FRWUpLb1pJaHZjTgpBUWtPTVRRd01qQXdCZ05WSFJFRUtUQW5naDl0WVhOMFpYSXRNUzVqYkhWemRHVnlMVEV1Wkc5aWNua3RhMjkwCkxuSjFod1FLQWdBZ01Bb0dDQ3FHU000OUJBTUNBMGNBTUVRQ0lBZ3lldkZneFYvWk1teVVDcFZnL2Nsc3djbzAKRS83UTFVdUppcE9CVHhGdEFpQUNhb2NiZjIxVTI5SmNVOStNM3RnaDdmemVOaGlKK2o1emZQdVFPZDB0TVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  signerName: kubernetes.io/kubelet-serving
  usages:
  - digital signature
  - key encipherment
  - server auth
  username: system:node:master-1.cluster-1.dobry-kot.ru
spec.signerName


apiVersion: mutations.gatekeeper.sh/v1beta1
kind: Assign
metadata:
  name: demo-privileged
spec:
  applyTo:
  - groups: ["certificates.k8s.io"]
    kinds: ["CertificateSigningRequest"]
    versions: ["v1"]
  match:
    scope: Cluster
    kinds:
    - apiGroups: ["*"]
      kinds: ["CertificateSigningRequest"]

  location: "spec.signerName"
  parameters:
    assign:
      value: "clusterissuers.cert-manager.io/vault-issuer"